// Code generated by go-enum-encoding; DO NOT EDIT.

package appleauth

import (
	"encoding/json/v2"
	"errors"
	"fmt"
	"math/rand"
	"slices"
	"testing"
)

func ExampleUserAgeRange_MarshalText() {
	for _, v := range []UserAgeRange{EmptyAppleAgeRange, UnknownAppleAgeRange, Child, NotChild} {
		b, _ := v.MarshalText()
		fmt.Printf("%s ", string(b))
	}
	// Output:  unknown child not_child
}

func ExampleUserAgeRange_UnmarshalText() {
	for _, s := range []string{"", "unknown", "child", "not_child"} {
		var v UserAgeRange
		if err := (&v).UnmarshalText([]byte(s)); err != nil {
			fmt.Println(err)
		}
	}
}

func TestUserAgeRange_MarshalText_UnmarshalText(t *testing.T) {
	for _, v := range []UserAgeRange{EmptyAppleAgeRange, UnknownAppleAgeRange, Child, NotChild} {
		b, err := v.MarshalText()
		if err != nil {
			t.Errorf("cannot encode: %s", err)
		}

		var d UserAgeRange
		if err := (&d).UnmarshalText(b); err != nil {
			t.Errorf("cannot decode: %s", err)
		}

		if d != v {
			t.Errorf("exp(%v) != got(%v)", v, d)
		}
	}

	t.Run("when unknown value, then error", func(t *testing.T) {
		s := `something`
		var v UserAgeRange
		err := (&v).UnmarshalText([]byte(s))
		if err == nil {
			t.Error("must be error")
		}
		if !errors.Is(err, ErrUnknownUserAgeRange) {
			t.Error("wrong error", err)
		}
	})
}

func TestUserAgeRange_JSON(t *testing.T) {
	type V struct {
		Values []UserAgeRange `json:"values"`
	}

	values := []UserAgeRange{EmptyAppleAgeRange, UnknownAppleAgeRange, Child, NotChild}

	var v V
	s := `{"values":["","unknown","child","not_child"]}`
	json.Unmarshal([]byte(s), &v)

	if len(v.Values) != len(values) {
		t.Errorf("cannot decode: %d", len(v.Values))
	}
	if !slices.Equal(v.Values, values) {
		t.Errorf("wrong decoded: %v", v.Values)
	}

	b, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("cannot encode: %s", err)
	}
	if string(b) != s {
		t.Errorf("wrong encoded: %s != %s", string(b), s)
	}

	t.Run("when unknown value, then error", func(t *testing.T) {
		s := `{"values":["something"]}`
		var v V
		err := json.Unmarshal([]byte(s), &v)
		if err == nil {
			t.Error("must be error")
		}
		if !errors.Is(err, ErrUnknownUserAgeRange) {
			t.Error("wrong error", err)
		}
	})
}

func BenchmarkUserAgeRange_UnmarshalText(b *testing.B) {
	vb := seq_bytes_UserAgeRange[rand.Intn(len(seq_bytes_UserAgeRange))]

	var x UserAgeRange

	for b.Loop() {
		_ = x.UnmarshalText(vb)
	}
}

func BenchmarkUserAgeRange_AppendText(b *testing.B) {
	bb := make([]byte, 10, 1000)

	vs := []UserAgeRange{EmptyAppleAgeRange, UnknownAppleAgeRange, Child, NotChild}
	v := vs[rand.Intn(len(vs))]

	for b.Loop() {
		_, _ = v.AppendText(bb)
	}
}

func BenchmarkUserAgeRange_MarshalText(b *testing.B) {
	vs := []UserAgeRange{EmptyAppleAgeRange, UnknownAppleAgeRange, Child, NotChild}
	v := vs[rand.Intn(len(vs))]

	for b.Loop() {
		_, _ = v.MarshalText()
	}
}

func TestUserAgeRange_String(t *testing.T) {
	values := []UserAgeRange{EmptyAppleAgeRange, UnknownAppleAgeRange, Child, NotChild}
	tags := []string{"", "unknown", "child", "not_child"}

	for i := range values {
		if s := values[i].String(); s != tags[i] {
			t.Error(s, tags[i])
		}
	}
}

func BenchmarkUserAgeRange_String(b *testing.B) {
	vs := []UserAgeRange{EmptyAppleAgeRange, UnknownAppleAgeRange, Child, NotChild}
	v := vs[rand.Intn(len(vs))]

	for b.Loop() {
		_ = v.String()
	}
}
