// Code generated by go-enum-encoding; DO NOT EDIT.

package appleauth

import "errors"

var ErrUnknownUserAgeRange = errors.New("unknown UserAgeRange")

func (s *UserAgeRange) UnmarshalText(text []byte) error {
	switch string(text) {
	case "":
		*s = EmptyAppleAgeRange
	case "unknown":
		*s = UnknownAppleAgeRange
	case "child":
		*s = Child
	case "not_child":
		*s = NotChild
	default:
		return ErrUnknownUserAgeRange
	}
	return nil
}

var seq_bytes_UserAgeRange = [...][]byte{[]byte(""), []byte("unknown"), []byte("child"), []byte("not_child")}

func (s UserAgeRange) MarshalText() ([]byte, error) { return s.AppendText(nil) }

func (s UserAgeRange) AppendText(b []byte) ([]byte, error) {
	switch s {
	case EmptyAppleAgeRange:
		return append(b, seq_bytes_UserAgeRange[0]...), nil
	case UnknownAppleAgeRange:
		return append(b, seq_bytes_UserAgeRange[1]...), nil
	case Child:
		return append(b, seq_bytes_UserAgeRange[2]...), nil
	case NotChild:
		return append(b, seq_bytes_UserAgeRange[3]...), nil
	default:
		return nil, ErrUnknownUserAgeRange
	}
}

var seq_string_UserAgeRange = [...]string{"", "unknown", "child", "not_child"}

func (s UserAgeRange) String() string {
	switch s {
	case EmptyAppleAgeRange:
		return seq_string_UserAgeRange[0]
	case UnknownAppleAgeRange:
		return seq_string_UserAgeRange[1]
	case Child:
		return seq_string_UserAgeRange[2]
	case NotChild:
		return seq_string_UserAgeRange[3]
	default:
		return ""
	}
}
